version: '3'

services:
    database:
        image: mysql:5.7
        container_name: mysql-docker
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_DATABASE: patientprod
            MYSQL_USER: root
            MYSQL_PASSWORD: rootroot
        volumes:
            - ./mysql_data:/var/lib/mysql
        networks:
            - ms-net

    patient:
        image: patient
        container_name: patient
        restart: always
        ports:
            - 8081:8081
        networks:
            - ms-net
        depends_on:
            - database

networks:
  ms-net:
      driver: bridge
